### GET school data, from user JonathanMartin123
GET http://localhost:3000/api/schools
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbmF0aGFuTWFydGluMTIzIiwiaWF0IjoxNzQ5NjE4MTc0LCJleHAiOjE3NDk3MDQ1NzR9.SRNJSp_oqKyD6uhFCjYO9-vLM17f0Y1ddtZrhLAFABc

### POST school data
POST http://localhost:3000/api/schools
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbmF0aGFuTWFydGluMTIzIiwiaWF0IjoxNzQ5NjAxNjg1LCJleHAiOjE3NDk2ODgwODV9.YdGW_tKUwxQNW44cJ3VDNACRwWZUzFiQR16y_XOHnUQ
Content-Type: application/json

{ "name": "Cool School"}

### POST quarter data
POST http://localhost:3000/api/quarters
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbmF0aGFuTWFydGluMTIzIiwiaWF0IjoxNzQ5NjE4MTc0LCJleHAiOjE3NDk3MDQ1NzR9.SRNJSp_oqKyD6uhFCjYO9-vLM17f0Y1ddtZrhLAFABc
Content-Type: application/json

{ "name": "Epic Quarter", "school": "Cool School"}

### POST course data
POST http://localhost:3000/api/classes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbmF0aGFuTWFydGluMTIzIiwiaWF0IjoxNzQ5NjE4MTc0LCJleHAiOjE3NDk3MDQ1NzR9.SRNJSp_oqKyD6uhFCjYO9-vLM17f0Y1ddtZrhLAFABc
Content-Type: application/json

{ "name": "Coolest Course", "quarter": "Epic Quarter", "school": "Cool School"}

### POST gradeRow data
POST http://localhost:3000/api/grades
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbmF0aGFuTWFydGluMTIzIiwiaWF0IjoxNzQ5NjE4MTc0LCJleHAiOjE3NDk3MDQ1NzR9.SRNJSp_oqKyD6uhFCjYO9-vLM17f0Y1ddtZrhLAFABc
Content-Type: application/json

{ 
    "catagory": "Extra Credit",
    "percentage": "100",
    "grade": "10",
    "class": "Coolest Course", 
    "quarter": "Epic Quarter", 
    "school": "Cool School"
}

### PATCH school data
PATCH http://localhost:3000/api/schools
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbmF0aGFuTWFydGluMTIzIiwiaWF0IjoxNzQ5NjE4MTc0LCJleHAiOjE3NDk3MDQ1NzR9.SRNJSp_oqKyD6uhFCjYO9-vLM17f0Y1ddtZrhLAFABc
Content-Type: application/json

{ "name": "Cool School", "newName": "Cooler School"}

### PATCH quarter data
PATCH http://localhost:3000/api/quarters
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbmF0aGFuTWFydGluMTIzIiwiaWF0IjoxNzQ5NjE4MTc0LCJleHAiOjE3NDk3MDQ1NzR9.SRNJSp_oqKyD6uhFCjYO9-vLM17f0Y1ddtZrhLAFABc
Content-Type: application/json

{ "name": "Epic Quarter", "newName": "Very Epic Quarter", "school": "Cooler School"}

### PATCH course data
PATCH http://localhost:3000/api/classes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbmF0aGFuTWFydGluMTIzIiwiaWF0IjoxNzQ5NjE4MTc0LCJleHAiOjE3NDk3MDQ1NzR9.SRNJSp_oqKyD6uhFCjYO9-vLM17f0Y1ddtZrhLAFABc
Content-Type: application/json

{ "name": "Coolest Course", "newName": "Cool Course", "quarter": "Very Epic Quarter", "school": "Cooler School"}

### PATCH gradeRow data
PATCH http://localhost:3000/api/grades
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbmF0aGFuTWFydGluMTIzIiwiaWF0IjoxNzQ5NjE4MTc0LCJleHAiOjE3NDk3MDQ1NzR9.SRNJSp_oqKyD6uhFCjYO9-vLM17f0Y1ddtZrhLAFABc
Content-Type: application/json

{ 
    "gradeRow": {
        "catagory": "Extra Credit",
        "percentage": "100",
        "grade": "10"
    },
    "newGradeRow":  {
        "catagory": "Extra Credit",
        "percentage": "100",
        "grade": "20"
    },
    "class": "Cool Course", 
    "quarter": "Very Epic Quarter", 
    "school": "Cooler School"
}

### DELETE school data
DELETE http://localhost:3000/api/schools
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbmF0aGFuTWFydGluMTIzIiwiaWF0IjoxNzQ5NjE4MTc0LCJleHAiOjE3NDk3MDQ1NzR9.SRNJSp_oqKyD6uhFCjYO9-vLM17f0Y1ddtZrhLAFABc
Content-Type: application/json

{ "name": "Cooler School"}

### DELETE quarter data
DELETE http://localhost:3000/api/quarters
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbmF0aGFuTWFydGluMTIzIiwiaWF0IjoxNzQ5NjE4MTc0LCJleHAiOjE3NDk3MDQ1NzR9.SRNJSp_oqKyD6uhFCjYO9-vLM17f0Y1ddtZrhLAFABc
Content-Type: application/json

{ "name": "Very Epic Quarter", "school": "Cooler School"}

### DELETE course data
DELETE http://localhost:3000/api/classes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbmF0aGFuTWFydGluMTIzIiwiaWF0IjoxNzQ5NjE4MTc0LCJleHAiOjE3NDk3MDQ1NzR9.SRNJSp_oqKyD6uhFCjYO9-vLM17f0Y1ddtZrhLAFABc
Content-Type: application/json

{ "name": "Cool Course", "quarter": "Very Epic Quarter", "school": "Cooler School"}

### DELETE gradeRow data
DELETE http://localhost:3000/api/grades
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvbmF0aGFuTWFydGluMTIzIiwiaWF0IjoxNzQ5NjE4MTc0LCJleHAiOjE3NDk3MDQ1NzR9.SRNJSp_oqKyD6uhFCjYO9-vLM17f0Y1ddtZrhLAFABc
Content-Type: application/json

{ 
    "gradeRow": {
        "catagory": "Extra Credit",
        "percentage": "100",
        "grade": "20"
    },
    "class": "Cool Course", 
    "quarter": "Very Epic Quarter", 
    "school": "Cooler School"
}

### New user registration
POST http://localhost:3000/auth/register
Content-Type: application/json

{ "username": "newuser", "password": "password" }

### Login success
POST http://localhost:3000/auth/login
Content-Type: application/json

{ "username": "JonathanMartin123", "password": "DelTaco123" }